### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by d-torrance** [seeschloss/wmcoincoin#3]
In commit ce30d18b, the version number in configure.ac is decremented from 2.6.2 to 2.6.1.  Meanwhile, the website has 2.6.3 available for download [1].

I'm just a little confused as to what to actually package for Debian.  Do you have any insight?

Thanks!

[1] http://hules.free.fr/wmcoincoin/download/wmcoincoin-2.6.3.tar.gz

**Comment by seeschloss** [comment]
Hmm... yeah, I had not really paid attention to version numbers in my repo until now, the "real" maintainer took care of them when creating the archives on his website, so I didn't bother.

But I should do it right, here, maybe with -git in the version number to make some distinction

Until the next commit which I'll make in a few minutes hopefully, the version number in this git repo has no meaning. Even if the version number doesn't say so, the repo is ahead of the package available on the site.

**Comment by d-torrance** [comment]
Great, thank you!
